name: .NET CI

on:
    push: 
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --logger "console;verbosity=detailed" | sed -e "s/Passed/$(printf '\033[0;32mPASS\033[0m')/" -e "s/Failed/$(printf '\033[0;31mFAIL\033[0m')/"
